@set allusersprofile=c:\programdata
@set appdata=c:\users\sergey\appdata\roaming
@set boost_inc=d:\sergey\codelibs\boost_1_62_0
@set boost_lib=d:\sergey\codelibs\boost_1_62_0\stage\lib
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-uat7lp8
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set gtk_basepath=c:\program files (x86)\gtksharp\2.12\
@set homedrive=c:
@set homepath=\users\sergey
@set include=c:\program files (x86)\microsoft visual studio 14.0\vc\include;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\shared;c:\program files (x86)\windows kits\10\include\10.0.14393.0\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\winrt
@set lib=c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references;c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\sergey\appdata\local
@set logonserver=\\desktop-uat7lp8
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set mysqlconnector_assembliespath=c:\program files (x86)\mysql\connector.net 6.9\assemblies\v4.5
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=2
@set onedrive=c:\users\sergey\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\common files\acronis\snapapi\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\mysql\mysql utilities 1.6\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\skype\phone\;c:\program files\nodejs\;c:\users\sergey\appdata\local\microsoft\windowsapps;c:\program files\opencppcoverage;c:\users\sergey\appdata\roaming\npm
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\sergey\appdata\local\temp\deva565.tmp
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 37 stepping 5, genuineintel
@set processor_level=6
@set processor_revision=2505
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\msbuild\
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\sergey\appdata\local\temp
@set tmp=c:\users\sergey\appdata\local\temp
@set ucrtversion=10.0.14393.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-uat7lp8
@set userdomain_roamingprofile=desktop-uat7lp8
@set username=thomas
@set userprofile=c:\users\sergey
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 14.0\vc\
@set visualstudiodir=d:\sergey\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio community 2015
@set visualstudioversion=14.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 14.0\
@set vslang=1033
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.14393.0\
@set windowssdkversion=10.0.14393.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" --driver-mode=cl @"D:\sergey\reps\OOP\6\HttpUrl\HttpUrl.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1